name: Manual CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        required: true
jobs:

  build-service:
    name: Build microservice
    runs-on: self-hosted
    env:
      DEVOPS_DIR: ${{ github.workspace}}/devops
      ARTIFACT_GEN_DIR: ${{ github.workspace }}/build/libs
      ARTIFACT_UNIQUE_ID: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_number }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build 

    - name: Share artifact to other jobs in the same workflow
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_UNIQUE_ID }}
        path: ${{ env.ARTIFACT_GEN_DIR }}/*.war
        if-no-files-found: error

  nightly-generate-docker-image-and-deploy-to-beanstalk:
      if: github.event.inputs.environment == 'nightly'
      name: Nightly - Build Image & Deploy to EB
      runs-on: self-hosted
      needs: build-service
      environment:
        name: nightly
      env:
        DEVOPS_DIR: ${{ github.workspace}}/devops
        ARTIFACT_UNIQUE_ID: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_number }}
        SERVICE_NAME: ${{ github.event.repository.name }}
        ENVIRONMENT: ${{ github.event.inputs.environment }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.sha }}

        - name: Configure AWS credentials from DevOps Tools account
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.DEVOPS_TOOLS_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.DEVOPS_TOOLS_AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          
        - name: Download artifact from previous job
          uses: actions/download-artifact@v2
          with:
            name: ${{ env.ARTIFACT_UNIQUE_ID }}
            path: ${{ env.DEVOPS_DIR }}

        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: demo
            IMAGE_TAG: ${{ env.ENVIRONMENT }}-${{ env.ARTIFACT_UNIQUE_ID }}
            DOCKER_JAVA_IMAGE_VERSION: latest
          run: |
            printf "dd.trace.enabled=true\ndd.service.name=${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}\ndd.agent.host=172.17.0.1\ndd.agent.port=8126" > $DEVOPS_DIR/dd_trace_agent.properties
            cp $DEVOPS_DIR/overrides/$ENVIRONMENT/supervisord.conf $DEVOPS_DIR
            cp $DEVOPS_DIR/overrides/$ENVIRONMENT/override.properties $DEVOPS_DIR
            docker build --build-arg JAVA_IMAGE_VERSION=$DOCKER_JAVA_IMAGE_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $DEVOPS_DIR
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG > $DEVOPS_DIR/ECR_DOCKER_APP_IMAGE_URL.txt

        - name: Prepare ebextensions and Docker credentials file 
          run: |
            ECR_IMAGE_TAG_URL=$(cat $DEVOPS_DIR/ECR_DOCKER_APP_IMAGE_URL.txt) && echo $ECR_IMAGE_TAG_URL
            cd $DEVOPS_DIR/beanstalk/ 
            sed "s,.\$.*\",\"${ECR_IMAGE_TAG_URL}\"," ./Dockerrun.aws.json.template > ./Dockerrun.aws.json
            zip -r ./sourcebundle.zip ./Dockerrun.aws.json ./.ebextensions -x ./*.template    

        - name: Deploy to Beanstalk nightly environment
          env:
            BEANSTALK_APPLICATION_NAME: ${{ github.event.repository.name }}
            BEANSTALK_ENVIRONMENT_NAME: ${{ github.event.repository.name }}-${{ env.ENVIRONMENT }}
          uses: einaregilsson/beanstalk-deploy@v16
          with:
            aws_access_key: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
            application_name: ${{ env.BEANSTALK_APPLICATION_NAME }}
            environment_name: ${{ env.BEANSTALK_ENVIRONMENT_NAME }}
            version_label: ${{ env.ARTIFACT_UNIQUE_ID }}
            region: us-east-1
            deployment_package: ${{ env.DEVOPS_DIR }}/beanstalk/sourcebundle.zip

  prod-generate-docker-image-and-deploy-to-beanstalk:
      if: github.ref == 'refs/heads/master' && github.event.inputs.environment == 'prod'
      name: Prod - Build Image & Deploy to EB
      runs-on: self-hosted
      environment:
        name: production
      env:
        DEVOPS_DIR: ${{ github.workspace}}/devops
        ARTIFACT_UNIQUE_ID: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_number }}
        SERVICE_NAME: ${{ github.event.repository.name }}
        ENVIRONMENT: ${{ github.event.inputs.environment }}
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.sha }}

        - name: Configure AWS credentials from DevOps Tools account
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.DEVOPS_TOOLS_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.DEVOPS_TOOLS_AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          
        - name: Download artifact from previous job
          uses: actions/download-artifact@v2
          with:
            name: ${{ env.ARTIFACT_UNIQUE_ID }}
            path: ${{ env.DEVOPS_DIR }}

        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: demo
            IMAGE_TAG: ${{ env.ENVIRONMENT }}-${{ env.ARTIFACT_UNIQUE_ID }}
            DOCKER_JAVA_IMAGE_VERSION: latest
          run: |
            printf "dd.trace.enabled=true\ndd.service.name=${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}\ndd.agent.host=172.17.0.1\ndd.agent.port=8126" > $DEVOPS_DIR/dd_trace_agent.properties
            cp $DEVOPS_DIR/overrides/$ENVIRONMENT/supervisord.conf $DEVOPS_DIR
            cp $DEVOPS_DIR/overrides/$ENVIRONMENT/override.properties $DEVOPS_DIR
            docker build --build-arg JAVA_IMAGE_VERSION=$DOCKER_JAVA_IMAGE_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $DEVOPS_DIR
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG > $DEVOPS_DIR/ECR_DOCKER_APP_IMAGE_URL.txt

        - name: Prepare ebextensions and Docker credentials file 
          run: |
            ECR_IMAGE_TAG_URL=$(cat $DEVOPS_DIR/ECR_DOCKER_APP_IMAGE_URL.txt) && echo $ECR_IMAGE_TAG_URL
            cd $DEVOPS_DIR/beanstalk/ 
            sed "s,.\$.*\",\"${ECR_IMAGE_TAG_URL}\"," ./Dockerrun.aws.json.template > ./Dockerrun.aws.json
            zip -r ./sourcebundle.zip ./Dockerrun.aws.json ./.ebextensions -x ./*.template    

        - name: Deploy to Beanstalk prod environment
          env:
            BEANSTALK_APPLICATION_NAME: ${{ github.event.repository.name }}
            BEANSTALK_ENVIRONMENT_NAME: ${{ github.event.repository.name }}-${{ env.ENVIRONMENT }}
          uses: einaregilsson/beanstalk-deploy@v16
          with:
            aws_access_key: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
            application_name: ${{ env.BEANSTALK_APPLICATION_NAME }}
            environment_name: ${{ env.BEANSTALK_ENVIRONMENT_NAME }}
            version_label: ${{ env.ARTIFACT_UNIQUE_ID }}
            region: us-east-1
            deployment_package: ${{ env.DEVOPS_DIR }}/beanstalk/sourcebundle.zip
