name: IaC Pipeline 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
  # pull_request:

jobs:
  Terraform:
    runs-on: ubuntu-latest
    environment:
      name: nightly
    steps:
      - uses: actions/checkout@v2
      
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      
      # Github PAT is used here instead of Github Token because only PAT can access private terraform modules
      - name: Configure Github PAT in Runner for pulling Private Terraform Modules
        env:
          GH_USER_NAME: SavvasArifMukhthar
          GH_USER_PAT: ${{ secrets.GH_USER_PAT }}
        run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://${GH_USER_NAME}:${GH_USER_PAT}@github.com/SavvasLearning".insteadOf "https://github.com/SavvasLearning"

      - name: Configure AWS Profiles in Runner
        run: |
          AWS_CREDENTIAL_CONFIG_FILE=~/.aws/config && mkdir $(dirname ${AWS_CREDENTIAL_CONFIG_FILE}) && touch $AWS_CREDENTIAL_CONFIG_FILE
          cat << EOF >> $AWS_CREDENTIAL_CONFIG_FILE
          [profile devops_tools]
          aws_access_key_id=${{ secrets.DEVOPS_TOOLS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.DEVOPS_TOOLS_AWS_SECRET_ACCESS_KEY }}
          [profile ${{ github.event.repository.name }}-nightly]
          aws_access_key_id=${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          EOF
      
      - name: Terraform Init
        working-directory: ${{ github.workspace }}/devops/terraform/staging
        id: init
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ github.workspace }}/devops/terraform/staging
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true
      
      - uses: SavvasLearning/terraform-pr-commenter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Using REPO default GITHUB_TOKEN here instead of GH_USER_PAT because the default token uses the built-in Bot to
        with:
          commenter_type: plan 
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
      
      # - uses: actions/github-script@0.9.0
      #   if: github.event_name == 'pull_request'
      #   env:
      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      #   with:
      #     github-token: ${{ secrets.GH_USER_PAT }}
      #     script: |
      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
      #       <details><summary>Show Plan</summary>
      #       \`\`\`${process.env.PLAN}\`\`\`
      #       </details>
      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: output
      #       })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
